version: '3.8'
networks:
  babnet:
    ipam:
      config:
        - subnet: 172.20.0.0/23

services:
  nanostore:
    hostname: 'nanostore'
    build: .
    depends_on: 
      - nanostore-mysql
    # volumes:
    #     - ".:/app"
    #   - "./src:/app/src"
    ports:
      - "8080:8080"
      - "9229:9229"
    networks:
      - babnet
    environment:
      ROUTING_PREFIX: ''
      MIGRATE_KEY: 'my-great-key'
      NODE_ENV: 'development'
      HOSTING_DOMAIN: 'http://localhost:8080'
      DOJO_URL: 'https://staging-dojo.babbage.systems'
      ADMIN_TOKEN: 'admin-token'
      HTTP_PORT: 8080
      PRICE_PER_GB_MO: 0.03
      UHRP_HOST_PRIVATE_KEY: '5KKGHf1dZpJ1L4aQTGCrVL4q3y5iwbcf9YcWS3oXynrWjaxS2LD'
      SERVER_PRIVATE_KEY: 'ab93af021feaab26a9adff360fc8a32da645539985a0adfcc2cecbfe76bb4e41'
      SERVER_XPRIV: 'xprv9s21ZrQH143K3GN3VANh6bt72CgqhysD35WrbZWq7zJMg9Jegv7qPhgCy1To8PHW8fJoa4EDLCx73FK8Ljfg64mW9XK9g13xkMwZKQPWZ9Y'
      MIN_HOSTING_MINUTES: 15
      GCP_BUCKET_NAME: 'staging-hashbrown.babbage.systems'
      GCP_PROJECT_ID: 'babbage-hashbrown'
      KNEX_CLIENT: 'mysql'
      KNEX_DB_CONNECTION: '{"port":3306,"host":"nanostore-mysql","user":"root","password":"test","database":"hashbrown"}'
      GOOGLE_APPLICATION_CREDENTIALS: '/app/storage-creds.json'

  nanostore-mysql:
    image: "mysql:8.0"
    platform: linux/x86_64
    hostname: 'nanostore-mysql'
    command: '--default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync'
    restart: always
    volumes:
      - './data/mysql-data:/var/lib/mysql'
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "hashbrown"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
