name: Production GAE Deployment
on:
  push:
    branches:
      - production
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Create .env file"
        run: "./scripts/mkenv.sh"
        env:
          NODE_ENV: ${{ secrets.PROD_NODE_ENV }}
          HOSTING_DOMAIN: ${{ secrets.PROD_HOSTING_DOMAIN }}
          ROUTING_PREFIX: ${{ secrets.PROD_ROUTING_PREFIX }}
          KNEX_DB_CONNECTION: ${{ secrets.PROD_KNEX_DB_CONNECTION }}
          KNEX_DB_CLIENT: ${{ secrets.PROD_KNEX_DB_CLIENT }}
          MIGRATE_KEY: ${{ secrets.PROD_MIGRATE_KEY }}
          PRICE_PER_GB_MO: ${{ secrets.PROD_PRICE_PER_GB_MO }}
          GCP_STORAGE_CREDS: ${{ secrets.PROD_GCP_STORAGE_CREDS }}
          GCP_BUCKET_NAME: ${{ secrets.PROD_GCP_BUCKET_NAME }}
          UHRP_HOST_PRIVATE_KEY: ${{ secrets.PROD_UHRP_HOST_PRIVATE_KEY }}
          SERVER_XPRIV: ${{ secrets.PROD_SERVER_XPRIV }}
          MIN_HOSTING_MINUTES: ${{ secrets.PROD_MIN_HOSTING_MINUTES }}
          GCP_PROJECT_ID: ${{ secrets.PROD_GCP_PROJECT_ID }}
          SERVER_PAYMAIL: ${{ secrets.PROD_SERVER_PAYMAIL }}
          CWI_NPM_TOKEN: ${{ secrets.CWI_NPM_TOKEN }}
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_deploy_creds }}
          deliverables: app.production.yaml
          