name: Staging GAE Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Create .env file"
        run: "./scripts/mkenv.sh"
        env:
          NODE_ENV: ${{ secrets.STAGING_NODE_ENV }}
          HOSTING_DOMAIN: ${{ secrets.STAGING_HOSTING_DOMAIN }}
          ROUTING_PREFIX: ${{ secrets.STAGING_ROUTING_PREFIX }}
          KNEX_DB_CONNECTION: ${{ secrets.STAGING_KNEX_DB_CONNECTION }}
          KNEX_DB_CLIENT: ${{ secrets.STAGING_KNEX_DB_CLIENT }}
          MIGRATE_KEY: ${{ secrets.STAGING_MIGRATE_KEY }}
          PRICE_PER_GB_MO: ${{ secrets.STAGING_PRICE_PER_GB_MO }}
          GCP_STORAGE_CREDS: ${{ secrets.STAGING_GCP_STORAGE_CREDS }}
          GCP_BUCKET_NAME: ${{ secrets.STAGING_GCP_BUCKET_NAME }}
          GCP_PROJECT_ID: ${{ secrets.STAGING_GCP_PROJECT_ID }}
          UHRP_HOST_PRIVATE_KEY: ${{ secrets.STAGING_UHRP_HOST_PRIVATE_KEY }}
          MIN_HOSTING_MINUTES: ${{ secrets.STAGING_MIN_HOSTING_MINUTES }}
          SERVER_PAYMAIL: ${{ secrets.STAGING_SERVER_PAYMAIL }}
          CWI_NPM_TOKEN: ${{ secrets.CWI_NPM_TOKEN }}
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_deploy_creds }}
          deliverables: app.staging.yaml
          